# Manual Backprop (Regression)

In [46]:
import numpy as np
import pandas as pd

In [47]:
df  = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['CGPA','profile_score','lpa'])
df

CGPA  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [48]:
def initialize_parameters(layers_dims):

    np.random.seed(3)
    parameters = {}
    L = len(layers_dims)            # number of layers in the network

    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layers_dims[l-1], layers_dims[l])) * 0.1
        parameters['b' + str(l)] = np.zeros((layers_dims[l], 1))

    return parameters

In [49]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [50]:
def linear_forward(A_prev, W, b):

    Z = np.dot(W.T, A_prev) + b

    return Z

In [51]:
# Forward propagation
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2  # number of layers in the neural network

    for l in range(1, L+1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        # print("A"+str(l-1), A_prev)
        # print("W"+str(l), Wl)
        # print("b"+str(l), bl)
        # print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        # print("A"+str(l), A)
        # print("=="*20)
    return A, A_prev # AL, A[L-1]

In [52]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [53]:
X = df[['CGPA','profile_score']].values[0].reshape(2,1) # Shape(no_of_features, no_of_examples)
y = df[['lpa']].values[0][0] # Shape(1, no_of_examples)
parameters = initialize_parameters([2,2,1]) # Shape(no_of_features, no_of_neurons)
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [54]:
X = df[['CGPA','profile_score']].values[0].reshape(2,1) # Shape(no_of_features, no_of_examples)
y = df[['lpa']].values[0][0] # Shape(1, no_of_examples)

y_hat , Al =L_layer_forward(X, parameters)
y_hat = y_hat[0][0]
update_parameters(parameters, y, y_hat, Al, X)

In [55]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [56]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['CGPA', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

# Keras

In [57]:
df  = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['CGPA','profile_score','lpa'])
df

CGPA  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [58]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [59]:
model =  Sequential()
model.add(Dense(2, input_dim=2, activation='linear'))
model.add(Dense(1, activation='linear'))

d:\DeepLearning\MLP(ANN)\.venv\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [60]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.get_weights()

[array([[ 0.7565969,  0.7327044],
        [ 0.9155041, -1.0467452]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.2981391],
        [ 0.0125972]], dtype=float32),
 array([0.], dtype=float32)]

In [62]:
new_weights = [np.ones((2,2)) * 0.1, np.zeros((2,)), np.ones((2,1)) * 0.1, np.zeros((1,))]
model.set_weights(new_weights)

In [63]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [64]:
optimizer = keras.optimizers.SGD(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mean_squared_error')

In [65]:
history = model.fit(df.iloc[:,0:-1].values, df['lpa'], epochs=100, verbose=1,batch_size=1)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 23.5375 
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 24.4947
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 16.4413
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.2280
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.2466
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.7096
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.7313
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.9164
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.6054
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.7444
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6917
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.8897
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.6197
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4657
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6823
Epoch 16/100
4/

In [66]:
model.get_weights()

[array([[-0.04148968, -0.04148968],
        [ 0.54623884,  0.54623884]], dtype=float32),
 array([0.01523481, 0.01523481], dtype=float32),
 array([[0.5375221],
        [0.5375221]], dtype=float32),
 array([0.09808856], dtype=float32)]